apiVersion: v1
kind: Pod
metadata:
  name: products-mongodb
  labels:
    app: products-mongodb
spec:
  volumes:
    - name: products-mongo-vol
      persistentVolumeClaim:
        claimName: products-pvc
  containers:
    - image: mongo
      name: container1
      command:
        - mongod
        - "--bind_ip"
        - "0.0.0.0"
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: products-mongo-vol
          mountPath: /data/db
