apiVersion: v1
kind: Service
metadata:
  labels:
    app: products-mongodb
  name: products-mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: products-mongodb
