apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-server
  template:
    metadata:
      labels:
        app: products-server
    spec:
      containers:
        - image: docker.io/rathidockerrepo/products-node-image:latest
          name: products-server
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: products-server
